window.inventoryBIPrototype = {
  meta: {
    title: "库存分析 BI 看板",
    stage: "静态原型首版",
    updatedAt: "2026年3月27日 04:23:16",
    sources: [
      { name: "库存分析BI看板.md", href: "./PRD/库存分析BI看板.md" },
      { name: "库存分析BI看板_前3层指标对应图表建议.md", href: "./PRD/库存分析BI看板_前3层指标对应图表建议.md" },
      { name: "库存分析BI看板_前3层页面线框图建议.md", href: "./PRD/库存分析BI看板_前3层页面线框图建议.md" },
    ],
  },
  layers: {
    layer1: {
      title: "库存战略总览看板",
      filters: [
        { label: "货号", value: "全部货号" },
        { label: "品类", value: "全部品类" },
        { label: "站点", value: "全部站点" },
        { label: "店铺", value: "全部店铺" },
        { label: "运营负责人", value: "全部负责人" },
        { label: "时间区间", value: "2026年3月-2026年3月" },
      ],
      kpiGroups: {
        inventoryScale: {
          title: "库存规模",
          hint: "库存快照口径，不随时间区间变化",
          showDeltas: false,
          metrics: [
            { title: "总库存量", value: "128,460", unit: "双", caption: "男鞋 + 女鞋 + 童鞋 + 在途" },
            { title: "总库存金额", value: "¥12,860,000", unit: "", caption: "库存资金占用" },
            { title: "在途库存量", value: "18,240", unit: "双", caption: "海运 / 空运 / 清关中" },
            { title: "FBA 在库数量", value: "54,900", unit: "双", caption: "平台仓鞋类在库快照" },
          ],
        },
        turnoverEfficiency: {
          title: "周转效率",
          hint: "受筛选条件影响",
          showDeltas: true,
          metrics: [
            {
              title: "库存周转天数",
              value: "47",
              unit: "天",
              caption: "统计期天数 / 库存周转次数",
              deltas: [
                { label: "MoM", value: "-1.8%", tone: "negative" },
                { label: "YoY", value: "-6.5%", tone: "negative" },
              ],
            },
            {
              title: "库存周转率",
              value: "1.92",
              unit: "次",
              caption: "销售成本 / 平均库存成本",
              deltas: [
                { label: "MoM", value: "+3.2%", tone: "positive" },
                { label: "YoY", value: "+5.8%", tone: "positive" },
              ],
            },
            {
              title: "动销比",
              value: "72.4",
              unit: "%",
              caption: "出库 SKU / 总 SKU",
              deltas: [
                { label: "MoM", value: "+1.1%", tone: "positive" },
                { label: "YoY", value: "+4.3%", tone: "positive" },
              ],
            },
            {
              title: "库销比",
              value: "1.38",
              unit: "",
              caption: "期末库存量 / 统计期销量",
              deltas: [
                { label: "MoM", value: "-2.4%", tone: "negative" },
                { label: "YoY", value: "-3.9%", tone: "negative" },
              ],
            },
          ],
        },
        fundingRisk: {
          title: "资金风险",
          hint: "支持数量/金额口径与仓别切换",
          valueTypeOptions: ["金额口径", "数量口径"],
          warehouseOptions: ["总体", "平台仓", "本地仓"],
          defaultValueType: "金额口径",
          defaultWarehouse: "总体",
          metricsByView: {
            金额口径: {
              总体: [
                { title: "资金周转率", value: "1.54", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "12.8", unit: "%", caption: "呆滞库存金额 / 总库存金额" },
                { title: "滞销库存占比", value: "9.6", unit: "%", caption: "滞销库存金额 / 总库存金额" },
                { title: "库容利用率", value: "78.3", unit: "%", caption: "总体仓容利用水平" },
              ],
              平台仓: [
                { title: "资金周转率", value: "1.62", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "10.2", unit: "%", caption: "平台仓呆滞金额占比" },
                { title: "滞销库存占比", value: "8.1", unit: "%", caption: "平台仓滞销金额占比" },
                { title: "库容利用率", value: "81.5", unit: "%", caption: "平台仓仓容利用率" },
              ],
              本地仓: [
                { title: "资金周转率", value: "1.43", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "15.4", unit: "%", caption: "本地仓呆滞金额占比" },
                { title: "滞销库存占比", value: "11.8", unit: "%", caption: "本地仓滞销金额占比" },
                { title: "库容利用率", value: "73.9", unit: "%", caption: "本地仓仓容利用率" },
              ],
            },
            数量口径: {
              总体: [
                { title: "资金周转率", value: "1.54", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "11.6", unit: "%", caption: "呆滞库存数量 / 总库存数量" },
                { title: "滞销库存占比", value: "8.8", unit: "%", caption: "滞销库存数量 / 总库存数量" },
                { title: "库容利用率", value: "78.3", unit: "%", caption: "总体仓容利用水平" },
              ],
              平台仓: [
                { title: "资金周转率", value: "1.62", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "9.4", unit: "%", caption: "平台仓呆滞数量占比" },
                { title: "滞销库存占比", value: "7.9", unit: "%", caption: "平台仓滞销数量占比" },
                { title: "库容利用率", value: "81.5", unit: "%", caption: "平台仓仓容利用率" },
              ],
              本地仓: [
                { title: "资金周转率", value: "1.43", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "14.3", unit: "%", caption: "本地仓呆滞数量占比" },
                { title: "滞销库存占比", value: "10.8", unit: "%", caption: "本地仓滞销数量占比" },
                { title: "库容利用率", value: "73.9", unit: "%", caption: "本地仓仓容利用率" },
              ],
            },
          },
        },
      },
      healthScore: {
        score: 81,
        grade: "良好",
        summary: "鞋类库存健康度处于良好区间，基础款周转稳定，但季节款与断码尾货导致呆滞风险偏高。",
        factors: [
          { label: "库存规模", value: 84, tone: "positive" },
          { label: "周转效率", value: 79, tone: "neutral" },
          { label: "资金风险", value: 74, tone: "warning" },
          { label: "仓容利用率", value: 87, tone: "positive" },
        ],
      },
      riskRatings: {
        summary: [
          { level: "高风险", count: 11, tone: "negative" },
          { level: "中风险", count: 21, tone: "warning" },
          { level: "低风险", count: 34, tone: "positive" },
        ],
        categories: [
          {
            category: "跑步鞋",
            level: "高风险",
            tone: "negative",
            stagnantRate: "31.8%",
            stockSalesRatio: "2.42",
            turnoverDays: "118 天",
            explanation: "41/42 码库存积压明显，导致呆滞率和周转天数同时偏高，需加快尺码结构清理。",
          },
          {
            category: "休闲板鞋",
            level: "中风险",
            tone: "warning",
            stagnantRate: "17.2%",
            stockSalesRatio: "1.68",
            turnoverDays: "79 天",
            explanation: "近 30 天销量走弱导致库销比上行，建议下调补货并同步推进折扣活动。",
          },
          {
            category: "女士高跟鞋",
            level: "高风险",
            tone: "negative",
            stagnantRate: "28.7%",
            stockSalesRatio: "2.09",
            turnoverDays: "109 天",
            explanation: "季节性需求回落后销量快速下滑，周转天数持续抬升，形成高风险积压。",
          },
          {
            category: "儿童运动鞋",
            level: "低风险",
            tone: "positive",
            stagnantRate: "7.6%",
            stockSalesRatio: "1.05",
            turnoverDays: "41 天",
            explanation: "补货节奏与销量匹配度较高，当前风险主要来自单站点促销波动。",
          },
        ],
      },
      trendScopeOptions: ["总体", "平台仓", "本地仓"],
      outboundInboundByScope: {
        总体: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [412, 426, 441, 458, 472, 486, 503, 519, 534, 548, 562, 577] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [468, 482, 495, 501, 508, 516, 523, 519, 510, 502, 494, 488] },
          ],
        },
        平台仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [301, 315, 326, 338, 351, 362, 374, 389, 401, 413, 426, 438] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [328, 336, 347, 354, 361, 368, 373, 369, 364, 358, 352, 345] },
          ],
        },
        本地仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [111, 113, 115, 120, 121, 124, 129, 130, 133, 135, 136, 139] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [140, 146, 148, 147, 147, 148, 150, 150, 146, 144, 142, 143] },
          ],
        },
      },
      balanceTrendByScope: {
        总体: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [1294, 1302, 1316, 1321, 1314, 1308, 1296, 1287, 1278, 1271, 1262, 1256] }],
        },
        平台仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [802, 807, 816, 821, 818, 811, 804, 798, 790, 784, 779, 772] }],
        },
        本地仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [492, 495, 500, 500, 496, 497, 492, 489, 488, 487, 483, 484] }],
        },
      },
      stagnantAnalysis: {
        sortOptions: ["按金额", "按数量"],
        defaultSort: "按金额",
        categoryTop10: {
          按金额: [
            { name: "跑步鞋", amount: 1240000, quantity: 18600 },
            { name: "休闲板鞋", amount: 1160000, quantity: 17420 },
            { name: "女士高跟鞋", amount: 1080000, quantity: 14980 },
            { name: "马丁靴", amount: 990000, quantity: 13260 },
            { name: "篮球鞋", amount: 930000, quantity: 12540 },
            { name: "儿童运动鞋", amount: 862000, quantity: 16680 },
            { name: "登山徒步鞋", amount: 805000, quantity: 9420 },
            { name: "凉鞋", amount: 768000, quantity: 15430 },
            { name: "皮鞋", amount: 724000, quantity: 9860 },
            { name: "帆布鞋", amount: 689000, quantity: 14320 },
          ],
          按数量: [
            { name: "跑步鞋", amount: 1240000, quantity: 18600 },
            { name: "休闲板鞋", amount: 1160000, quantity: 17420 },
            { name: "儿童运动鞋", amount: 862000, quantity: 16680 },
            { name: "凉鞋", amount: 768000, quantity: 15430 },
            { name: "女士高跟鞋", amount: 1080000, quantity: 14980 },
            { name: "帆布鞋", amount: 689000, quantity: 14320 },
            { name: "马丁靴", amount: 990000, quantity: 13260 },
            { name: "篮球鞋", amount: 930000, quantity: 12540 },
            { name: "皮鞋", amount: 724000, quantity: 9860 },
            { name: "登山徒步鞋", amount: 805000, quantity: 9420 },
          ],
        },
        warehouseTop10: {
          按金额: [
            { name: "华东鞋靴本地仓", amount: 1660000, quantity: 23420 },
            { name: "华南鞋靴本地仓", amount: 1480000, quantity: 21060 },
            { name: "美西鞋类平台仓", amount: 1320000, quantity: 19340 },
            { name: "欧盟鞋类平台仓", amount: 1210000, quantity: 17180 },
            { name: "美东鞋类平台仓", amount: 1130000, quantity: 16240 },
            { name: "日本鞋类平台仓", amount: 1020000, quantity: 14820 },
            { name: "英国鞋类平台仓", amount: 960000, quantity: 13960 },
            { name: "加拿大鞋类平台仓", amount: 902000, quantity: 13110 },
            { name: "华北鞋靴本地仓", amount: 856000, quantity: 12460 },
            { name: "华中鞋靴本地仓", amount: 812000, quantity: 11780 },
          ],
          按数量: [
            { name: "华东鞋靴本地仓", amount: 1660000, quantity: 23420 },
            { name: "华南鞋靴本地仓", amount: 1480000, quantity: 21060 },
            { name: "美西鞋类平台仓", amount: 1320000, quantity: 19340 },
            { name: "欧盟鞋类平台仓", amount: 1210000, quantity: 17180 },
            { name: "美东鞋类平台仓", amount: 1130000, quantity: 16240 },
            { name: "日本鞋类平台仓", amount: 1020000, quantity: 14820 },
            { name: "英国鞋类平台仓", amount: 960000, quantity: 13960 },
            { name: "加拿大鞋类平台仓", amount: 902000, quantity: 13110 },
            { name: "华北鞋靴本地仓", amount: 856000, quantity: 12460 },
            { name: "华中鞋靴本地仓", amount: 812000, quantity: 11780 },
          ],
        },
      },
    },
    layer2: {
      badge: "第二层 · 面向采购 / 运营 / 计划",
      title: "多维结构分析看板",
      summary: "聚焦库存结构是否合理，帮助识别畅销品缺货与滞销品积压的具体位置，为结构优化提供依据。",
      tags: ["结构占比", "排名对比", "库龄分布"],
      filters: [
        { label: "时间范围", value: "近 90 天" },
        { label: "国家 / 站点", value: "全站点 / 可切换" },
        { label: "仓库", value: "全部仓库" },
        { label: "品类", value: "全部品类" },
        { label: "系列", value: "全部系列" },
      ],
      modules: [
        {
          title: "ABC 分类库存分布",
          description: "用于展示高价值高动销、中价值中频次、低价值低动销库存的金额占比、SKU 占比和占用库位。",
          chart: "建议图表：堆积条形图 / 矩形树图",
          note: "重点看 A/B/C 三类结构是否失衡。",
        },
        {
          title: "SKU 周转速度排名",
          description: "同时保留高周转 Top 10 和低周转 Bottom 10 的位置，便于采购和运营在同一屏幕里看快慢两端。",
          chart: "建议图表：横向排名条形图",
          note: "重点看 MSKU、周转天数、日均销量与库存金额。",
        },
        {
          title: "库存结构对比图",
          description: "对比库存占比与销售占比，直接发现某些品类库存压得多但卖得少的结构性问题。",
          chart: "建议图表：分组柱状图 / 哑铃图",
          note: "重点看库存占比与销售占比之间的差距。",
        },
        {
          title: "库龄结构图",
          description: "先保留静态库龄结构与库龄变化趋势两个区块，后续可按 FBA 仓和 CN 仓拆开。",
          chart: "建议图表：堆积柱状图 + 堆积面积图",
          note: "重点看 0-30、31-60、61-90、90+ 等区间迁移。",
        },
        {
          title: "超期仓储费预警",
          description: "这里先预留费用预估和风险 SKU 清单的组合布局，用于后续补充长期仓储费与超龄附加费试算。",
          chart: "建议图表：预警表 + 横向条形图",
          note: "重点看 181-365 天与 365 天以上库存。",
        },
        {
          title: "不可售库存池",
          description: "按退货、损坏、过期等原因拆分不可售库存，同时保留处理截止日期与责任动作的显示位置。",
          chart: "建议图表：结构图 + 状态列表",
          note: "重点看原因占比与自动移除期限。",
        },
      ],
    },
    layer3: {
      badge: "第三层 · 面向一线运营 / 采购 / 计划",
      title: "动态预警与补货建议看板",
      summary: "以执行为中心，把断货预警、补货建议、时间决策与差异闭环放在同一层，方便业务快速处理。",
      tags: ["执行导向", "主表优先", "时间轴决策"],
      filters: [
        { label: "时间范围", value: "近 30 天" },
        { label: "国家 / 站点", value: "多站点切换" },
        { label: "系列", value: "全部系列" },
        { label: "运营", value: "全部运营" },
        { label: "货号", value: "全部货号" },
        { label: "紧急程度", value: "全部等级" },
      ],
      modules: [
        {
          title: "库存预警模块",
          description: "先把断货数量、断货比例、FBA 可售时间和必断货 SKU 的摘要区与主表位置固定下来。",
          chart: "建议图表：预警卡片 + 条件格式明细表",
          note: "重点看红黄绿灯机制与风险可读性。",
        },
        {
          title: "补货建议模块",
          description: "为需采购数量、预计断货日期、建议下单日期和紧急等级保留矩阵表与条形对比区。",
          chart: "建议图表：矩阵表 + 分组柱状图",
          note: "重点看正常 / 加急 / 必断货三档节奏。",
        },
        {
          title: "销量预测与库存水位预测图",
          description: "这里保留实际库存、预测库存和安全库存线的主图位置，后续适合叠加三条曲线。",
          chart: "建议图表：多折线图",
          note: "重点看未来缺货日期与连续补货策略。",
        },
        {
          title: "收发差异看板",
          description: "先固定差异明细表、超期未上架预警和差异根因分析三块的位置关系。",
          chart: "建议图表：主表 + 老化条形图 + 根因条形图",
          note: "重点看物流商、仓库、品类差异。",
        },
        {
          title: "索赔状态追踪",
          description: "保留待调查、已开 Case、索赔成功、已驳回等状态的闭环展示区，便于后续补流程图。",
          chart: "建议图表：漏斗图 / 状态看板",
          note: "重点看索赔处理阶段与金额挽回统计。",
        },
      ],
    },
    layer4: {
      badge: "第四层 · 面向数据分析员 / 供应链专家",
      title: "问题诊断与参数模拟看板",
      summary: "本层用于做根因定位、参数模拟和策略试验。由于当前只有需求文档依据，本轮先保留模块骨架，不预设图表细节。",
      tags: ["问题诊断", "参数模拟", "后续强化交互"],
      filters: [
        { label: "时间范围", value: "近 90 天" },
        { label: "国家 / 站点", value: "全站点" },
        { label: "仓库 / 物流商", value: "待后续接入" },
      ],
      modules: [
        {
          title: "SKU 周转矩阵",
          description: "预留畅销缺货、畅销安全、滞销积压、滞销安全四类问题 SKU 的分析区域。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补四象限图与问题聚类规则。",
        },
        {
          title: "安全库存模型模拟",
          description: "预留服务系数、需求偏差和提前期参数的模拟面板位置。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补滑块、模拟结果和 What-If 交互。",
        },
        {
          title: "提前期敏感性分析",
          description: "预留不同物流商、运输方式和政策变化对库存水平影响的展示区。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补敏感性曲线和对比视图。",
        },
        {
          title: "全链路库存分布",
          description: "预留供应商生产中、国内仓、在途、清关、待上架、FBA 可售等全链路库存分布位置。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补漏斗或分段流转视图。",
        },
        {
          title: "交期与时效偏差分析",
          description: "预留供应商延期、头程延误和差异趋势预警的组合分析区。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补偏差趋势图与预警规则展示。",
        },
      ],
    },
  },
};
