window.inventoryBIPrototype = {
  meta: {
    title: "库存分析 BI 看板",
    stage: "静态原型首版",
    updatedAt: "2026年3月27日 04:23:16",
    sources: [
      { name: "库存分析BI看板.md", href: "./PRD/库存分析BI看板.md" },
      { name: "库存分析BI看板_前3层指标对应图表建议.md", href: "./PRD/库存分析BI看板_前3层指标对应图表建议.md" },
      { name: "库存分析BI看板_前3层页面线框图建议.md", href: "./PRD/库存分析BI看板_前3层页面线框图建议.md" },
    ],
  },
  layers: {
    layer1: {
      title: "库存战略总览看板",
      filters: [
        { label: "货号", value: "全部货号" },
        { label: "品类", value: "全部品类" },
        { label: "站点", value: "全部站点" },
        { label: "店铺", value: "全部店铺" },
        { label: "运营负责人", value: "全部负责人" },
        { label: "时间区间", value: "2026年3月-2026年3月" },
      ],
      kpiGroups: {
        inventoryScale: {
          title: "库存规模",
          hint: "库存快照口径，不随时间区间变化",
          showDeltas: false,
          metrics: [
            { title: "总库存量", value: "128,460", unit: "双", caption: "本地仓+在途+平台仓" },
            { title: "总库存金额", value: "¥12,860,000", unit: "", caption: "总库存量成本金额" },
            { title: "在途库存量", value: "18,240", unit: "双", caption: "物流在途" },
            { title: "FBA 在库数量", value: "54,900", unit: "双", caption: "平台仓在库快照" },
          ],
        },
        turnoverEfficiency: {
          title: "周转效率",
          hint: "受筛选条件影响",
          showDeltas: true,
          metrics: [
            {
              title: "库存周转天数",
              value: "47",
              unit: "天",
              caption: "统计期天数 / 库存周转次数",
              deltas: [
                { label: "MoM", value: "-1.8%", tone: "negative" },
                { label: "YoY", value: "-6.5%", tone: "negative" },
              ],
            },
            {
              title: "库存周转率",
              value: "1.92",
              unit: "次",
              caption: "销售成本 / 平均库存成本",
              deltas: [
                { label: "MoM", value: "+3.2%", tone: "positive" },
                { label: "YoY", value: "+5.8%", tone: "positive" },
              ],
            },
            {
              title: "动销比",
              value: "72.4",
              unit: "%",
              caption: "出库 SKU / 总 SKU",
              deltas: [
                { label: "MoM", value: "+1.1%", tone: "positive" },
                { label: "YoY", value: "+4.3%", tone: "positive" },
              ],
            },
            {
              title: "库销比",
              value: "1.38",
              unit: "",
              caption: "期末库存量 / 统计期销量",
              deltas: [
                { label: "MoM", value: "-2.4%", tone: "negative" },
                { label: "YoY", value: "-3.9%", tone: "negative" },
              ],
            },
          ],
        },
        fundingRisk: {
          title: "资金风险",
          hint: "支持数量/金额口径与仓别切换",
          valueTypeOptions: ["金额口径", "数量口径"],
          warehouseOptions: ["总体", "平台仓", "本地仓"],
          defaultValueType: "金额口径",
          defaultWarehouse: "总体",
          metricsByView: {
            金额口径: {
              总体: [
                { title: "资金周转率", value: "1.54", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "12.8", unit: "%", caption: "呆滞库存金额 / 总库存金额" },
                { title: "滞销库存占比", value: "9.6", unit: "%", caption: "滞销库存金额 / 总库存金额" },
                { title: "库容利用率", value: "78.3", unit: "%", caption: "总体仓容利用水平" },
              ],
              平台仓: [
                { title: "资金周转率", value: "1.62", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "10.2", unit: "%", caption: "平台仓呆滞金额占比" },
                { title: "滞销库存占比", value: "8.1", unit: "%", caption: "平台仓滞销金额占比" },
                { title: "库容利用率", value: "81.5", unit: "%", caption: "平台仓仓容利用率" },
              ],
              本地仓: [
                { title: "资金周转率", value: "1.43", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "15.4", unit: "%", caption: "本地仓呆滞金额占比" },
                { title: "滞销库存占比", value: "11.8", unit: "%", caption: "本地仓滞销金额占比" },
                { title: "库容利用率", value: "73.9", unit: "%", caption: "本地仓仓容利用率" },
              ],
            },
            数量口径: {
              总体: [
                { title: "资金周转率", value: "1.54", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "11.6", unit: "%", caption: "呆滞库存数量 / 总库存数量" },
                { title: "滞销库存占比", value: "8.8", unit: "%", caption: "滞销库存数量 / 总库存数量" },
                { title: "库容利用率", value: "78.3", unit: "%", caption: "总体仓容利用水平" },
              ],
              平台仓: [
                { title: "资金周转率", value: "1.62", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "9.4", unit: "%", caption: "平台仓呆滞数量占比" },
                { title: "滞销库存占比", value: "7.9", unit: "%", caption: "平台仓滞销数量占比" },
                { title: "库容利用率", value: "81.5", unit: "%", caption: "平台仓仓容利用率" },
              ],
              本地仓: [
                { title: "资金周转率", value: "1.43", unit: "", caption: "暂占位，待业务确认保留" },
                { title: "呆滞库存率", value: "14.3", unit: "%", caption: "本地仓呆滞数量占比" },
                { title: "滞销库存占比", value: "10.8", unit: "%", caption: "本地仓滞销数量占比" },
                { title: "库容利用率", value: "73.9", unit: "%", caption: "本地仓仓容利用率" },
              ],
            },
          },
        },
      },
      healthScore: {
        score: 81,
        grade: "良好",
        summary: "鞋类库存健康度处于良好区间，基础款周转稳定，但季节款与断码尾货导致呆滞风险偏高。",
        factors: [
          { label: "库存规模", value: 84, tone: "positive" },
          { label: "周转效率", value: 79, tone: "neutral" },
          { label: "资金风险", value: 74, tone: "warning" },
          { label: "仓容利用率", value: 87, tone: "positive" },
        ],
      },
      riskRatings: {
        summary: [
          { level: "高风险", count: 11, tone: "negative" },
          { level: "中风险", count: 21, tone: "warning" },
          { level: "低风险", count: 34, tone: "positive" },
        ],
        categories: [
          {
            category: "跑步鞋",
            level: "高风险",
            tone: "negative",
            stagnantRate: "31.8%",
            stockSalesRatio: "2.42",
            turnoverDays: "118 天",
            explanation: "41/42 码库存积压明显，导致呆滞率和周转天数同时偏高，需加快尺码结构清理。",
          },
          {
            category: "休闲板鞋",
            level: "中风险",
            tone: "warning",
            stagnantRate: "17.2%",
            stockSalesRatio: "1.68",
            turnoverDays: "79 天",
            explanation: "近 30 天销量走弱导致库销比上行，建议下调补货并同步推进折扣活动。",
          },
          {
            category: "女士高跟鞋",
            level: "高风险",
            tone: "negative",
            stagnantRate: "28.7%",
            stockSalesRatio: "2.09",
            turnoverDays: "109 天",
            explanation: "季节性需求回落后销量快速下滑，周转天数持续抬升，形成高风险积压。",
          },
          {
            category: "儿童运动鞋",
            level: "低风险",
            tone: "positive",
            stagnantRate: "7.6%",
            stockSalesRatio: "1.05",
            turnoverDays: "41 天",
            explanation: "补货节奏与销量匹配度较高，当前风险主要来自单站点促销波动。",
          },
        ],
      },
      trendScopeOptions: ["总体", "平台仓", "本地仓"],
      outboundInboundByScope: {
        总体: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [412, 426, 441, 458, 472, 486, 503, 519, 534, 548, 562, 577] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [468, 482, 495, 501, 508, 516, 523, 519, 510, 502, 494, 488] },
          ],
        },
        平台仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [301, 315, 326, 338, 351, 362, 374, 389, 401, 413, 426, 438] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [328, 336, 347, 354, 361, 368, 373, 369, 364, 358, 352, 345] },
          ],
        },
        本地仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [
            { name: "出库量", color: "#0f7068", fill: "#0f7068", data: [111, 113, 115, 120, 121, 124, 129, 130, 133, 135, 136, 139] },
            { name: "入库量", color: "#bf7b22", fill: "#bf7b22", data: [140, 146, 148, 147, 147, 148, 150, 150, 146, 144, 142, 143] },
          ],
        },
      },
      balanceTrendByScope: {
        总体: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [1294, 1302, 1316, 1321, 1314, 1308, 1296, 1287, 1278, 1271, 1262, 1256] }],
        },
        平台仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [802, 807, 816, 821, 818, 811, 804, 798, 790, 784, 779, 772] }],
        },
        本地仓: {
          labels: ["01-03", "01-11", "01-19", "01-27", "02-04", "02-12", "02-20", "02-28", "03-07", "03-15", "03-23", "03-31"],
          series: [{ name: "库存余额", color: "#4d7397", fill: "#4d7397", area: true, data: [492, 495, 500, 500, 496, 497, 492, 489, 488, 487, 483, 484] }],
        },
      },
      stagnantAnalysis: {
        sortOptions: ["按金额", "按数量"],
        defaultSort: "按金额",
        categoryTop10: {
          按金额: [
            { name: "跑步鞋", amount: 1240000, quantity: 18600 },
            { name: "休闲板鞋", amount: 1160000, quantity: 17420 },
            { name: "女士高跟鞋", amount: 1080000, quantity: 14980 },
            { name: "马丁靴", amount: 990000, quantity: 13260 },
            { name: "篮球鞋", amount: 930000, quantity: 12540 },
            { name: "儿童运动鞋", amount: 862000, quantity: 16680 },
            { name: "登山徒步鞋", amount: 805000, quantity: 9420 },
            { name: "凉鞋", amount: 768000, quantity: 15430 },
            { name: "皮鞋", amount: 724000, quantity: 9860 },
            { name: "帆布鞋", amount: 689000, quantity: 14320 },
          ],
          按数量: [
            { name: "跑步鞋", amount: 1240000, quantity: 18600 },
            { name: "休闲板鞋", amount: 1160000, quantity: 17420 },
            { name: "儿童运动鞋", amount: 862000, quantity: 16680 },
            { name: "凉鞋", amount: 768000, quantity: 15430 },
            { name: "女士高跟鞋", amount: 1080000, quantity: 14980 },
            { name: "帆布鞋", amount: 689000, quantity: 14320 },
            { name: "马丁靴", amount: 990000, quantity: 13260 },
            { name: "篮球鞋", amount: 930000, quantity: 12540 },
            { name: "皮鞋", amount: 724000, quantity: 9860 },
            { name: "登山徒步鞋", amount: 805000, quantity: 9420 },
          ],
        },
        warehouseTop10: {
          按金额: [
            { name: "华东鞋靴本地仓", amount: 1660000, quantity: 23420 },
            { name: "华南鞋靴本地仓", amount: 1480000, quantity: 21060 },
            { name: "美西鞋类平台仓", amount: 1320000, quantity: 19340 },
            { name: "欧盟鞋类平台仓", amount: 1210000, quantity: 17180 },
            { name: "美东鞋类平台仓", amount: 1130000, quantity: 16240 },
            { name: "日本鞋类平台仓", amount: 1020000, quantity: 14820 },
            { name: "英国鞋类平台仓", amount: 960000, quantity: 13960 },
            { name: "加拿大鞋类平台仓", amount: 902000, quantity: 13110 },
            { name: "华北鞋靴本地仓", amount: 856000, quantity: 12460 },
            { name: "华中鞋靴本地仓", amount: 812000, quantity: 11780 },
          ],
          按数量: [
            { name: "华东鞋靴本地仓", amount: 1660000, quantity: 23420 },
            { name: "华南鞋靴本地仓", amount: 1480000, quantity: 21060 },
            { name: "美西鞋类平台仓", amount: 1320000, quantity: 19340 },
            { name: "欧盟鞋类平台仓", amount: 1210000, quantity: 17180 },
            { name: "美东鞋类平台仓", amount: 1130000, quantity: 16240 },
            { name: "日本鞋类平台仓", amount: 1020000, quantity: 14820 },
            { name: "英国鞋类平台仓", amount: 960000, quantity: 13960 },
            { name: "加拿大鞋类平台仓", amount: 902000, quantity: 13110 },
            { name: "华北鞋靴本地仓", amount: 856000, quantity: 12460 },
            { name: "华中鞋靴本地仓", amount: 812000, quantity: 11780 },
          ],
        },
      },
    },
    layer2: {
      title: "多维结构分析看板",
      filters: [
        { label: "货号", value: "全部货号" },
        { label: "品类", value: "全部品类" },
        { label: "站点", value: "全部站点" },
        { label: "店铺", value: "全部店铺" },
        { label: "运营负责人", value: "全部负责人" },
        { label: "时间区间", value: "2026年3月-2026年3月" },
      ],
      abcDistribution: {
        note: "A/B/C 按动销贡献率分层，默认排除淘汰品与新品。",
        dimensionOptions: ["品类", "SKU", "仓库", "国家"],
        metricOptions: ["库存金额", "SKU数量", "库位占用"],
        defaultDimension: "品类",
        defaultMetric: "库存金额",
        dataByDimension: {
          品类: {
            库存金额: [
              { tier: "A类", value: 66, color: "#0f7068" },
              { tier: "B类", value: 23, color: "#bf7b22" },
              { tier: "C类", value: 11, color: "#cb5a48" },
            ],
            SKU数量: [
              { tier: "A类", value: 49, color: "#0f7068" },
              { tier: "B类", value: 31, color: "#bf7b22" },
              { tier: "C类", value: 20, color: "#cb5a48" },
            ],
            库位占用: [
              { tier: "A类", value: 55, color: "#0f7068" },
              { tier: "B类", value: 28, color: "#bf7b22" },
              { tier: "C类", value: 17, color: "#cb5a48" },
            ],
          },
          SKU: {
            库存金额: [
              { tier: "A类", value: 71, color: "#0f7068" },
              { tier: "B类", value: 19, color: "#bf7b22" },
              { tier: "C类", value: 10, color: "#cb5a48" },
            ],
            SKU数量: [
              { tier: "A类", value: 52, color: "#0f7068" },
              { tier: "B类", value: 30, color: "#bf7b22" },
              { tier: "C类", value: 18, color: "#cb5a48" },
            ],
            库位占用: [
              { tier: "A类", value: 58, color: "#0f7068" },
              { tier: "B类", value: 27, color: "#bf7b22" },
              { tier: "C类", value: 15, color: "#cb5a48" },
            ],
          },
          仓库: {
            库存金额: [
              { tier: "A类", value: 62, color: "#0f7068" },
              { tier: "B类", value: 26, color: "#bf7b22" },
              { tier: "C类", value: 12, color: "#cb5a48" },
            ],
            SKU数量: [
              { tier: "A类", value: 47, color: "#0f7068" },
              { tier: "B类", value: 33, color: "#bf7b22" },
              { tier: "C类", value: 20, color: "#cb5a48" },
            ],
            库位占用: [
              { tier: "A类", value: 53, color: "#0f7068" },
              { tier: "B类", value: 29, color: "#bf7b22" },
              { tier: "C类", value: 18, color: "#cb5a48" },
            ],
          },
          国家: {
            库存金额: [
              { tier: "A类", value: 58, color: "#0f7068" },
              { tier: "B类", value: 29, color: "#bf7b22" },
              { tier: "C类", value: 13, color: "#cb5a48" },
            ],
            SKU数量: [
              { tier: "A类", value: 45, color: "#0f7068" },
              { tier: "B类", value: 35, color: "#bf7b22" },
              { tier: "C类", value: 20, color: "#cb5a48" },
            ],
            库位占用: [
              { tier: "A类", value: 50, color: "#0f7068" },
              { tier: "B类", value: 32, color: "#bf7b22" },
              { tier: "C类", value: 18, color: "#cb5a48" },
            ],
          },
        },
      },
      turnoverRanking: {
        top10: [
          { parent: "RUN-轻量跑鞋父体", turnoverDays: 24, dailySales: 182, stockQty: 4380, stockAmount: 892000 },
          { parent: "KID-儿童训练鞋父体", turnoverDays: 27, dailySales: 165, stockQty: 3960, stockAmount: 764000 },
          { parent: "SNE-透气板鞋父体", turnoverDays: 29, dailySales: 154, stockQty: 4120, stockAmount: 838000 },
          { parent: "BSK-实战篮球鞋父体", turnoverDays: 31, dailySales: 146, stockQty: 4290, stockAmount: 915000 },
          { parent: "TRK-越野徒步鞋父体", turnoverDays: 33, dailySales: 131, stockQty: 3650, stockAmount: 802000 },
          { parent: "CNS-经典帆布鞋父体", turnoverDays: 35, dailySales: 126, stockQty: 3410, stockAmount: 618000 },
          { parent: "CLS-通勤皮鞋父体", turnoverDays: 36, dailySales: 119, stockQty: 3340, stockAmount: 703000 },
          { parent: "SLP-舒适拖鞋父体", turnoverDays: 38, dailySales: 114, stockQty: 3270, stockAmount: 482000 },
          { parent: "SND-夏季凉鞋父体", turnoverDays: 39, dailySales: 108, stockQty: 3190, stockAmount: 566000 },
          { parent: "SNK-基础休闲鞋父体", turnoverDays: 41, dailySales: 102, stockQty: 3120, stockAmount: 598000 },
        ],
        bottom10: [
          { parent: "HL-宴会高跟鞋父体", turnoverDays: 122, dailySales: 19, stockQty: 2340, stockAmount: 712000 },
          { parent: "BT-冬季马丁靴父体", turnoverDays: 117, dailySales: 22, stockQty: 2470, stockAmount: 846000 },
          { parent: "LF-乐福鞋旧款父体", turnoverDays: 113, dailySales: 24, stockQty: 2190, stockAmount: 652000 },
          { parent: "RNR-复古跑鞋父体", turnoverDays: 109, dailySales: 28, stockQty: 2630, stockAmount: 738000 },
          { parent: "DS-设计师联名父体", turnoverDays: 105, dailySales: 31, stockQty: 2010, stockAmount: 934000 },
          { parent: "WTR-雨靴父体", turnoverDays: 101, dailySales: 33, stockQty: 2260, stockAmount: 508000 },
          { parent: "HR-高帮板鞋父体", turnoverDays: 97, dailySales: 36, stockQty: 2390, stockAmount: 626000 },
          { parent: "CLB-商务短靴父体", turnoverDays: 94, dailySales: 38, stockQty: 2270, stockAmount: 688000 },
          { parent: "SLM-瘦长楦型父体", turnoverDays: 92, dailySales: 40, stockQty: 2160, stockAmount: 574000 },
          { parent: "PRM-溢价系列父体", turnoverDays: 89, dailySales: 43, stockQty: 2050, stockAmount: 782000 },
        ],
      },
      structureCompare: {
        scopeOptions: ["总体", "平台仓", "本地仓"],
        defaultScope: "总体",
        labels: ["跑步鞋", "休闲鞋", "篮球鞋", "高跟鞋", "童鞋", "靴类"],
        sales: [860, 740, 620, 510, 690, 430],
        inventoryByScope: {
          总体: [1320, 1180, 980, 860, 1020, 790],
          平台仓: [840, 760, 620, 510, 680, 430],
          本地仓: [480, 420, 360, 350, 340, 360],
        },
      },
      agingStructure: {
        warehouseOptions: ["FBA仓", "CN仓"],
        defaultWarehouse: "FBA仓",
        dataByWarehouse: {
          FBA仓: {
            share: [
              { label: "0-30天", value: 41, color: "#0f7068" },
              { label: "31-60天", value: 24, color: "#2d8b65" },
              { label: "61-90天", value: 14, color: "#4d7397" },
              { label: "91-180天", value: 11, color: "#bf7b22" },
              { label: "181-365天", value: 6, color: "#cb5a48" },
              { label: "365天以上", value: 4, color: "#9a3324" },
            ],
            trend: {
              labels: ["1月", "2月", "3月"],
              series: [
                { name: "0-60天", color: "#0f7068", fill: "#0f7068", area: true, data: [65, 64, 62] },
                { name: "61-180天", color: "#bf7b22", fill: "#bf7b22", area: true, data: [24, 25, 26] },
                { name: "181天以上", color: "#cb5a48", fill: "#cb5a48", area: true, data: [11, 11, 12] },
              ],
            },
          },
          CN仓: {
            share: [
              { label: "0-30天", value: 28, color: "#0f7068" },
              { label: "31-60天", value: 21, color: "#2d8b65" },
              { label: "61-90天", value: 18, color: "#4d7397" },
              { label: "91-180天", value: 17, color: "#bf7b22" },
              { label: "181-365天", value: 10, color: "#cb5a48" },
              { label: "365天以上", value: 6, color: "#9a3324" },
            ],
            trend: {
              labels: ["1月", "2月", "3月"],
              series: [
                { name: "0-60天", color: "#0f7068", fill: "#0f7068", area: true, data: [52, 50, 49] },
                { name: "61-180天", color: "#bf7b22", fill: "#bf7b22", area: true, data: [33, 34, 34] },
                { name: "181天以上", color: "#cb5a48", fill: "#cb5a48", area: true, data: [15, 16, 17] },
              ],
            },
          },
        },
      },
      storageFeeWarning: {
        month: "2026年4月",
        ltsfSkuCount: 132,
        estimatedLtsf: 286000,
        estimatedAgedFee: 194000,
        estimatedTotal: 480000,
        bands: [
          { range: "181-365天", skuCount: 86, volume: "52.4 m³", rate: "¥3.6 / m³", fee: 188000 },
          { range: "365天以上", skuCount: 46, volume: "31.1 m³", rate: "¥9.4 / m³", fee: 292000 },
        ],
        topRiskSkus: [
          { sku: "RUN-41-BLK-US", warehouse: "FBA-USW", age: "392天", fee: 13200 },
          { sku: "HL-38-RED-EU", warehouse: "FBA-EU", age: "417天", fee: 11800 },
          { sku: "BT-42-BRN-US", warehouse: "FBA-USE", age: "381天", fee: 10600 },
          { sku: "CLB-40-BLK-UK", warehouse: "FBA-UK", age: "365天", fee: 9600 },
          { sku: "LF-39-WHT-JP", warehouse: "FBA-JP", age: "358天", fee: 8900 },
        ],
      },
      unsellablePool: {
        totalQty: 7040,
        totalAmount: 1326000,
        reasons: [
          { reason: "买家退货", qty: 3240, amount: 418000, share: 46, color: "#0f7068" },
          { reason: "FBA仓库损坏", qty: 2310, amount: 596000, share: 33, color: "#bf7b22" },
          { reason: "过期", qty: 1490, amount: 312000, share: 21, color: "#cb5a48" },
        ],
        deadlines: [
          { sku: "RUN-42-WHT-US", reason: "买家退货", action: "自动移除", deadline: "2026-04-08", daysLeft: 11 },
          { sku: "SNE-40-GRY-EU", reason: "FBA仓库损坏", action: "弃置", deadline: "2026-04-12", daysLeft: 15 },
          { sku: "KID-33-BLU-US", reason: "买家退货", action: "自动移除", deadline: "2026-04-15", daysLeft: 18 },
          { sku: "HL-37-RED-UK", reason: "过期", action: "弃置", deadline: "2026-04-18", daysLeft: 21 },
          { sku: "BT-41-BRN-JP", reason: "FBA仓库损坏", action: "自动移除", deadline: "2026-04-20", daysLeft: 23 },
          { sku: "CNS-39-BLK-CA", reason: "过期", action: "弃置", deadline: "2026-04-24", daysLeft: 27 },
        ],
      },
    },
    layer3: {
      badge: "第三层 · 面向一线运营 / 采购 / 计划",
      title: "动态预警与补货建议看板",
      summary: "以执行为中心，把断货预警、补货建议、时间决策与差异闭环放在同一层，方便业务快速处理。",
      tags: ["执行导向", "主表优先", "时间轴决策"],
      filters: [
        { label: "时间范围", value: "近 30 天" },
        { label: "国家 / 站点", value: "多站点切换" },
        { label: "系列", value: "全部系列" },
        { label: "运营", value: "全部运营" },
        { label: "货号", value: "全部货号" },
        { label: "紧急程度", value: "全部等级" },
      ],
      modules: [
        {
          title: "库存预警模块",
          description: "先把断货数量、断货比例、FBA 可售时间和必断货 SKU 的摘要区与主表位置固定下来。",
          chart: "建议图表：预警卡片 + 条件格式明细表",
          note: "重点看红黄绿灯机制与风险可读性。",
        },
        {
          title: "补货建议模块",
          description: "为需采购数量、预计断货日期、建议下单日期和紧急等级保留矩阵表与条形对比区。",
          chart: "建议图表：矩阵表 + 分组柱状图",
          note: "重点看正常 / 加急 / 必断货三档节奏。",
        },
        {
          title: "销量预测与库存水位预测图",
          description: "这里保留实际库存、预测库存和安全库存线的主图位置，后续适合叠加三条曲线。",
          chart: "建议图表：多折线图",
          note: "重点看未来缺货日期与连续补货策略。",
        },
        {
          title: "收发差异看板",
          description: "先固定差异明细表、超期未上架预警和差异根因分析三块的位置关系。",
          chart: "建议图表：主表 + 老化条形图 + 根因条形图",
          note: "重点看物流商、仓库、品类差异。",
        },
        {
          title: "索赔状态追踪",
          description: "保留待调查、已开 Case、索赔成功、已驳回等状态的闭环展示区，便于后续补流程图。",
          chart: "建议图表：漏斗图 / 状态看板",
          note: "重点看索赔处理阶段与金额挽回统计。",
        },
      ],
    },
    layer4: {
      badge: "第四层 · 面向数据分析员 / 供应链专家",
      title: "问题诊断与参数模拟看板",
      summary: "本层用于做根因定位、参数模拟和策略试验。由于当前只有需求文档依据，本轮先保留模块骨架，不预设图表细节。",
      tags: ["问题诊断", "参数模拟", "后续强化交互"],
      filters: [
        { label: "时间范围", value: "近 90 天" },
        { label: "国家 / 站点", value: "全站点" },
        { label: "仓库 / 物流商", value: "待后续接入" },
      ],
      modules: [
        {
          title: "SKU 周转矩阵",
          description: "预留畅销缺货、畅销安全、滞销积压、滞销安全四类问题 SKU 的分析区域。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补四象限图与问题聚类规则。",
        },
        {
          title: "安全库存模型模拟",
          description: "预留服务系数、需求偏差和提前期参数的模拟面板位置。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补滑块、模拟结果和 What-If 交互。",
        },
        {
          title: "提前期敏感性分析",
          description: "预留不同物流商、运输方式和政策变化对库存水平影响的展示区。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补敏感性曲线和对比视图。",
        },
        {
          title: "全链路库存分布",
          description: "预留供应商生产中、国内仓、在途、清关、待上架、FBA 可售等全链路库存分布位置。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补漏斗或分段流转视图。",
        },
        {
          title: "交期与时效偏差分析",
          description: "预留供应商延期、头程延误和差异趋势预警的组合分析区。",
          chart: "图表方案：本轮仅保留占位",
          note: "后续再补偏差趋势图与预警规则展示。",
        },
      ],
    },
  },
};
